[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino

lib_deps =
    jgromes/RadioLib

monitor_speed = 115200

extra_scripts = post:uf2_post.py